<?php
$nomeConstrutora = "Construtech";

$categorias = [
    'bruto' => 'Bruto',
    'ferramentas' => 'Ferramentas',
    'acabamento' => 'Acabamento'
];


$produtos_base = [
[
    'codigo_produto' => 1,
    'nome' => 'Porcelanato Chicargo Gray',
    'preco' => 114.54,
    'categoria' => 'acabamento',
    'quantidade' => 80,
    'qtd_minima' => 10,
    'qtd_maxima' => 200,
    'descricao' => 'Visual moderno e urbano, ideal para ambientes sofisticados',
    'imagem' => './imagens/piso',
    ],

    [
    'codigo_produto' => 2,
    'nome' => 'Argamassa Quartzolit',
    'preco' => 31.35,
    'categoria' => 'acabamento',
    'quantidade' => 74,
    'qtd_minima' => 20,
    'qtd_maxima' => 200,
    'descricao' => 'Essencial para instalar pisos e revestimentos com boa fixação',
    'imagem' => './imagens/argamassa',
    ],
    [
    'codigo_produto' => 3,
    'nome' => 'Torneira Banheiro Quadrada Cromada',
    'preco' => 33.00,
    'categoria' => 'acabamento',
    'quantidade' => 50,
    'qtd_minima' => 20,
    'qtd_maxima' => 200,
    'descricao' => 'Modelo básico, resistente e barato para lavatórios',
    'imagem' => './imagens/torneira',
    ],
    [
    'codigo_produto' => 7,
    'nome' => 'Cimento Votoran',
    'preco' => 34.87,
    'categoria' => 'bruto',
    'quantidade' => 20,
    'qtd_minima' => 20,
    'qtd_maxima' => 200,
    'descricao' => 'Modelo popular com boa trabalhabilidade para obras gerais',
    'imagem' => './imagens/cimento.webp',
    ],
    [
    'codigo_produto' => 8,
    'nome' => 'Areia Lavada Ensacada',
    'preco' => 5.99,
    'categoria' => 'bruto',
    'quantidade' => 100,
    'qtd_minima' => 38,
    'qtd_maxima' => 200,
    'descricao' => 'Areia limpa pronta para uso em argamassa e concreto',
    'imagem' => './imagens/areia.jpg',
    ],
    [

    'codigo_produto' => 9,
    'nome' => 'Tijolo Cerâmico 8 Furos',
    'preco' => 1.29,
    'categoria' => 'bruto',
    'quantidade' => 580,
    'qtd_minima' => 20,
    'qtd_maxima' => 200,
    'descricao' => 'Modelo básico, resistente e barato para lavatórios',
    'imagem' => './imagens/tijolo',
    ],
    [
    'codigo_produto' => 4,
    'nome' => 'Martelo',
    'preco' => 23.90,
    'categoria' => 'ferramentas',
    'quantidade' => 85,
    'qtd_minima' => 10,
    'qtd_maxima' => 100,
    'descricao' => 'Cabeça forjada e temperada em aço especial, garantindo grande resistência ao produto',
    'imagem' => './imagens/martelo.jpg',
    ],
    [
    'codigo_produto' => 5,
    'nome' => 'Furadeira',
    'preco' => 320.00,
    'categoria' => 'ferramentas',
    'quantidade' => 20,
    'qtd_minima' => 5,
    'qtd_maxima' => 120,
    'descricao' => '750W + martelete: perfuração eficiente em concreto',
    'imagem' => './imagens/furadeira.jpg',
    ],
    [
    'codigo_produto' => 6,
    'nome' => 'Chave de fenda',
    'preco' => 12.00,
    'categoria' => 'ferramentas',
    'quantidade' => 200,
    'qtd_minima' => 20,
    'qtd_maxima' => 300,
    'descricao' => 'Possui ponta magnetizada que facilita tanto a colocação quanto a retirada de parafusos em locais de difícil acesso. Conta ainda com cabo anatômico que proporciona maior conforto ao operador.',
    'imagem' => './imagens/chavedefenda.webp',
    ],
    [
    'codigo_produto' => 10,
    'nome' => ':3',
    'preco' => 12.00,
    'categoria' => 'ferramentas',
    'quantidade' => 200,
    'qtd_minima' => 20,
    'qtd_maxima' => 300,
    'descricao' => 'meow meow meow meow meow meow',
    'imagem' => './imagens/cta.jpg',
    ]

];